import{a as h,i as n,S as y}from"./assets/vendor-B6jJ9_I0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const L=r=>r.reduce((o,t)=>o+`
      <li class="gallery-card">
        <a class="gallery-link" href="${t.largeImageURL}">
          <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="gallery-info">
          <p><span>Likes:</span> ${t.likes}</p>
          <p><span>Views:</span> ${t.views}</p>
          <p><span>Comments:</span> ${t.comments}</p>
          <p><span>Downloads:</span> ${t.downloads}</p>
        </div>
      </li>
    `,"");h.defaults.baseURL="https://pixabay.com/api";const b=async(r,o)=>{const t={q:r,key:"47683521-7bc13f64e806eb93b38e1f294",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o};try{return(await h.get("/",{params:t})).data}catch(a){throw console.error("Error fetching data from Pixabay:",a),a}},w=document.querySelector(".js-search-form"),p=document.querySelector(".js-gallery"),i=document.querySelector(".js-load-more"),m=document.querySelector(".js-loader");let u,c=1,l="";const v=()=>{n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})},f=()=>{p.innerHTML=""},g=async()=>{try{i.classList.add("is-hidden");const r=await b(l,c);if(r.totalHits===0){n.error({message:`Sorry, there are no images matching your search query "${l}". Please try again!`,position:"topRight",timeout:3e3}),f(),i.classList.add("is-hidden");return}const{hits:o,totalHits:t}=r;p.insertAdjacentHTML("beforeend",L(o)),u?u.refresh():u=new y(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250}),c*15>=t?(i.classList.add("is-hidden"),v()):i.classList.remove("is-hidden");const a=p.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}catch(r){n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight",timeout:3e3}),console.error(r)}finally{m.classList.add("is-hidden")}},E=async r=>{if(r.preventDefault(),l=r.currentTarget.elements.user_query.value.trim(),c=1,l===""){n.error({message:"Please enter a search word",position:"topRight",timeout:3e3});return}f(),i.classList.add("is-hidden"),m.classList.remove("is-hidden"),await g()},P=async()=>{c++,m.classList.remove("is-hidden"),await g()};w.addEventListener("submit",E);i.addEventListener("click",P);
//# sourceMappingURL=index.js.map
