import{a as h,i as n,S as y}from"./assets/vendor-B6jJ9_I0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const L=r=>r.reduce((o,e)=>o+`
      <li class="gallery-card">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="gallery-info">
          <p><span>Likes:</span> ${e.likes}</p>
          <p><span>Views:</span> ${e.views}</p>
          <p><span>Comments:</span> ${e.comments}</p>
          <p><span>Downloads:</span> ${e.downloads}</p>
        </div>
      </li>
    `,"");h.defaults.baseURL="https://pixabay.com/api";const b=async r=>{const o={q:r,key:"47683521-7bc13f64e806eb93b38e1f294",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15};try{return(await h.get("/",{params:o})).data}catch(e){throw console.error("Error fetching data from Pixabay:",e),e}},w=document.querySelector(".js-search-form"),p=document.querySelector(".js-gallery"),a=document.querySelector(".js-load-more"),m=document.querySelector(".js-loader");let u,c=1,l="";const v=()=>{n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})},f=()=>{p.innerHTML=""},g=async()=>{try{const r=await b(l,c);if(r.totalHits===0){n.error({message:`Sorry, there are no images matching your search query "${l}". Please try again!`,position:"topRight",timeout:3e3}),f(),a.classList.add("is-hidden");return}const{hits:o,totalHits:e}=r;p.insertAdjacentHTML("beforeend",L(o)),u?u.refresh():u=new y(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250}),c*15>=e?(a.classList.add("is-hidden"),v()):a.classList.remove("is-hidden");const i=p.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}catch(r){n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight",timeout:3e3}),console.error(r)}finally{m.classList.add("is-hidden")}},E=async r=>{if(r.preventDefault(),l=r.currentTarget.elements.user_query.value.trim(),c=1,l===""){n.error({message:"Please enter a search word",position:"topRight",timeout:3e3});return}f(),a.classList.add("is-hidden"),m.classList.remove("is-hidden"),await g()},P=async()=>{c++,m.classList.remove("is-hidden"),await g()};w.addEventListener("submit",E);a.addEventListener("click",P);
//# sourceMappingURL=index.js.map
